-- ============================================================================
-- Saptham CMS — FULL BACKEND BUNDLE
-- GENERATED by scripts/bundle-sql.mjs — do not edit.
-- Paste this whole file into the Supabase SQL Editor and Run.
-- Safe to re-run (every statement is idempotent / upserting).
-- ============================================================================


-- ==========================================================================
-- BEGIN supabase/migrations/20260718090001_schema.sql
-- ==========================================================================

-- ============================================================================
-- Saptham CMS — STEP 1 · Tables
--
-- Deliberately plain SQL: no extensions, no auth.* foreign keys, no nested
-- dollar-quoting. The Supabase SQL Editor runs a pasted script as ONE
-- transaction, so a single failing statement rolls back everything — this file
-- avoids every construct that can fail on a locked-down project.
--
-- gen_random_uuid() is built into PostgreSQL 13+ (no pgcrypto needed).
-- Idempotent: safe to re-run.
-- ============================================================================

-- ─── Enums ──────────────────────────────────────────────────────────────────
do $$ begin
  create type public.event_type as enum
    ('production','festival','workshop','competition','symposium','other');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.performance_type as enum
    ('dance','vocal','instrumental','drama','fusion','other');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.sponsor_tier as enum
    ('title','gold','silver','bronze','partner','supporter');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.message_status as enum
    ('new','read','replied','archived','spam');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.media_kind as enum
    ('image','video','audio','document','other');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.announcement_priority as enum
    ('low','normal','high','urgent');
exception when duplicate_object then null; end $$;

-- ─── Helpers ────────────────────────────────────────────────────────────────

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- Admin registry. RLS needs an admin predicate. `user_id` holds an auth.users
-- id but carries no FK: adding one requires REFERENCES on the auth schema,
-- which is not guaranteed to be grantable in the SQL Editor.
create table if not exists public.admin_users (
  user_id     uuid primary key,
  email       text,
  note        text,
  created_at  timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.admin_users a where a.user_id = auth.uid());
$$;

grant execute on function public.is_admin() to anon, authenticated;

-- ─── office_bearers ─────────────────────────────────────────────────────────
create table if not exists public.office_bearers (
  id             uuid primary key default gen_random_uuid(),
  full_name      text not null,
  role           text not null,
  department     text,
  academic_year  text not null,
  image_path     text,
  bio            text,
  email          text,
  phone          text,
  social         jsonb not null default '{}'::jsonb,
  display_order  integer not null default 0,
  is_published   boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  constraint office_bearers_unique_per_year unique (full_name, academic_year)
);
create index if not exists office_bearers_year_order_idx
  on public.office_bearers (academic_year, display_order);

-- ─── alumni ─────────────────────────────────────────────────────────────────
create table if not exists public.alumni (
  id              uuid primary key default gen_random_uuid(),
  full_name       text not null,
  role            text,
  tenure          text,
  graduation_year smallint,
  quote           text,
  image_path      text,
  display_order   integer not null default 0,
  is_featured     boolean not null default true,
  is_published    boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint alumni_unique_person unique (full_name, tenure)
);
create index if not exists alumni_order_idx on public.alumni (display_order);

-- ─── events ─────────────────────────────────────────────────────────────────
create table if not exists public.events (
  id               uuid primary key default gen_random_uuid(),
  slug             text not null unique,
  title            text not null,
  subtitle         text,
  description      text,
  event_type       public.event_type not null default 'other',
  event_date       date,
  venue            text,
  cover_image_path text,
  display_order    integer not null default 0,
  is_published     boolean not null default true,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index if not exists events_type_order_idx on public.events (event_type, display_order);

-- ─── event_gallery ──────────────────────────────────────────────────────────
create table if not exists public.event_gallery (
  id            uuid primary key default gen_random_uuid(),
  event_id      uuid references public.events(id) on delete cascade,
  category      text,
  image_path    text not null,
  caption       text,
  alt_text      text,
  display_order integer not null default 0,
  is_published  boolean not null default true,
  created_at    timestamptz not null default now()
);
create index if not exists event_gallery_event_idx on public.event_gallery (event_id, display_order);
create index if not exists event_gallery_category_idx on public.event_gallery (category, display_order);

-- ─── performances ───────────────────────────────────────────────────────────
create table if not exists public.performances (
  id               uuid primary key default gen_random_uuid(),
  event_id         uuid references public.events(id) on delete set null,
  title            text not null,
  performance_type public.performance_type not null default 'other',
  description      text,
  performers       text[] not null default '{}',
  raga             text,
  tala             text,
  video_url        text,
  performed_on     date,
  display_order    integer not null default 0,
  is_published     boolean not null default true,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index if not exists performances_event_idx on public.performances (event_id, display_order);

-- ─── achievements ───────────────────────────────────────────────────────────
create table if not exists public.achievements (
  id            uuid primary key default gen_random_uuid(),
  title         text not null,
  description   text,
  awarding_body text,
  category      text,
  awarded_on    date,
  image_path    text,
  display_order integer not null default 0,
  is_published  boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ─── announcements ──────────────────────────────────────────────────────────
create table if not exists public.announcements (
  id           uuid primary key default gen_random_uuid(),
  title        text not null,
  body         text,
  link_url     text,
  priority     public.announcement_priority not null default 'normal',
  starts_at    timestamptz not null default now(),
  ends_at      timestamptz,
  is_published boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists announcements_window_idx on public.announcements (starts_at, ends_at);

-- ─── sponsors ───────────────────────────────────────────────────────────────
create table if not exists public.sponsors (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  tier          public.sponsor_tier not null default 'supporter',
  logo_path     text,
  website_url   text,
  description   text,
  display_order integer not null default 0,
  is_published  boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists sponsors_tier_idx on public.sponsors (tier, display_order);

-- ─── contact_messages ───────────────────────────────────────────────────────
create table if not exists public.contact_messages (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  email       text not null,
  subject     text,
  message     text not null,
  status      public.message_status not null default 'new',
  source      text not null default 'website',
  admin_notes text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists contact_messages_status_idx on public.contact_messages (status, created_at desc);

-- ─── media_assets ───────────────────────────────────────────────────────────
create table if not exists public.media_assets (
  id          uuid primary key default gen_random_uuid(),
  bucket      text not null,
  path        text not null,
  kind        public.media_kind not null default 'image',
  title       text,
  alt_text    text,
  caption     text,
  mime_type   text,
  size_bytes  bigint,
  width       integer,
  height      integer,
  checksum    text,
  uploaded_by uuid,
  created_at  timestamptz not null default now(),
  constraint media_assets_unique_object unique (bucket, path)
);

-- ─── settings ───────────────────────────────────────────────────────────────
create table if not exists public.settings (
  key         text primary key,
  value       jsonb not null default '{}'::jsonb,
  description text,
  is_public   boolean not null default true,
  updated_at  timestamptz not null default now()
);

-- ─── updated_at triggers ────────────────────────────────────────────────────
drop trigger if exists set_updated_at on public.office_bearers;
create trigger set_updated_at before update on public.office_bearers
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.alumni;
create trigger set_updated_at before update on public.alumni
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.events;
create trigger set_updated_at before update on public.events
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.performances;
create trigger set_updated_at before update on public.performances
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.achievements;
create trigger set_updated_at before update on public.achievements
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.announcements;
create trigger set_updated_at before update on public.announcements
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.sponsors;
create trigger set_updated_at before update on public.sponsors
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.contact_messages;
create trigger set_updated_at before update on public.contact_messages
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.settings;
create trigger set_updated_at before update on public.settings
  for each row execute function public.set_updated_at();

-- END supabase/migrations/20260718090001_schema.sql


-- ==========================================================================
-- BEGIN supabase/migrations/20260718090002_rls.sql
-- ==========================================================================

-- ============================================================================
-- Saptham CMS — STEP 2 · Row Level Security
--
-- Model:
--   • anon / authenticated  → SELECT published rows on public content only
--   • contact_messages      → INSERT-only for the public, never readable
--   • admin_users members   → full read/write everywhere (public.is_admin())
--   • settings              → only rows flagged is_public are world-readable
--
-- Written as plain, explicit statements (no DO loops, no nested dollar-quoting)
-- so that any failure names the exact table it happened on.
--
-- NOTE: "enable" only, never "force". FORCE would subject the table OWNER to
-- RLS too, blocking the STEP 4 seed inserts and any service_role maintenance.
-- Idempotent.
-- ============================================================================

alter table public.admin_users       enable row level security;
alter table public.office_bearers    enable row level security;
alter table public.alumni            enable row level security;
alter table public.events            enable row level security;
alter table public.event_gallery     enable row level security;
alter table public.performances      enable row level security;
alter table public.achievements      enable row level security;
alter table public.announcements     enable row level security;
alter table public.sponsors          enable row level security;
alter table public.contact_messages  enable row level security;
alter table public.media_assets      enable row level security;
alter table public.settings          enable row level security;

-- ─── office_bearers ─────────────────────────────────────────────────────────
drop policy if exists public_read_published on public.office_bearers;
create policy public_read_published on public.office_bearers
  for select to anon, authenticated using (is_published = true);

drop policy if exists admin_all on public.office_bearers;
create policy admin_all on public.office_bearers
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─── alumni ─────────────────────────────────────────────────────────────────
drop policy if exists public_read_published on public.alumni;
create policy public_read_published on public.alumni
  for select to anon, authenticated using (is_published = true);

drop policy if exists admin_all on public.alumni;
create policy admin_all on public.alumni
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─── events ─────────────────────────────────────────────────────────────────
drop policy if exists public_read_published on public.events;
create policy public_read_published on public.events
  for select to anon, authenticated using (is_published = true);

drop policy if exists admin_all on public.events;
create policy admin_all on public.events
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─── event_gallery ──────────────────────────────────────────────────────────
drop policy if exists public_read_published on public.event_gallery;
create policy public_read_published on public.event_gallery
  for select to anon, authenticated using (is_published = true);

drop policy if exists admin_all on public.event_gallery;
create policy admin_all on public.event_gallery
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─── performances ───────────────────────────────────────────────────────────
drop policy if exists public_read_published on public.performances;
create policy public_read_published on public.performances
  for select to anon, authenticated using (is_published = true);

drop policy if exists admin_all on public.performances;
create policy admin_all on public.performances
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─── achievements ───────────────────────────────────────────────────────────
drop policy if exists public_read_published on public.achievements;
create policy public_read_published on public.achievements
  for select to anon, authenticated using (is_published = true);

drop policy if exists admin_all on public.achievements;
create policy admin_all on public.achievements
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─── sponsors ───────────────────────────────────────────────────────────────
drop policy if exists public_read_published on public.sponsors;
create policy public_read_published on public.sponsors
  for select to anon, authenticated using (is_published = true);

drop policy if exists admin_all on public.sponsors;
create policy admin_all on public.sponsors
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─── announcements: published AND inside its live window ────────────────────
drop policy if exists public_read_active on public.announcements;
create policy public_read_active on public.announcements
  for select to anon, authenticated
  using (
    is_published = true
    and starts_at <= now()
    and (ends_at is null or ends_at > now())
  );

drop policy if exists admin_all on public.announcements;
create policy admin_all on public.announcements
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─── contact_messages: write-only inbox ─────────────────────────────────────
-- Anyone may submit; nobody but an admin may read. The absence of a SELECT
-- policy for anon is what makes the table unreadable from the browser.
drop policy if exists anyone_can_submit on public.contact_messages;
create policy anyone_can_submit on public.contact_messages
  for insert to anon, authenticated
  with check (status = 'new' and admin_notes is null);

drop policy if exists admin_read_messages on public.contact_messages;
create policy admin_read_messages on public.contact_messages
  for select to authenticated using (public.is_admin());

drop policy if exists admin_update_messages on public.contact_messages;
create policy admin_update_messages on public.contact_messages
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists admin_delete_messages on public.contact_messages;
create policy admin_delete_messages on public.contact_messages
  for delete to authenticated using (public.is_admin());

-- ─── media_assets: public read (the files are public anyway), admin write ───
drop policy if exists public_read_media on public.media_assets;
create policy public_read_media on public.media_assets
  for select to anon, authenticated using (true);

drop policy if exists admin_all on public.media_assets;
create policy admin_all on public.media_assets
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─── settings: only explicitly public keys are exposed ──────────────────────
drop policy if exists public_read_public_settings on public.settings;
create policy public_read_public_settings on public.settings
  for select to anon, authenticated using (is_public = true);

drop policy if exists admin_all on public.settings;
create policy admin_all on public.settings
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ─── admin_users: self-read, admin-manage ───────────────────────────────────
drop policy if exists read_own_admin_row on public.admin_users;
create policy read_own_admin_row on public.admin_users
  for select to authenticated
  using (user_id = auth.uid() or public.is_admin());

drop policy if exists admin_manage_admins on public.admin_users;
create policy admin_manage_admins on public.admin_users
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- END supabase/migrations/20260718090002_rls.sql


-- ==========================================================================
-- BEGIN supabase/migrations/20260718090004_grants.sql
-- ==========================================================================

-- ============================================================================
-- STEP 5 — ROLE GRANTS
-- ============================================================================
-- RLS answers "which rows may this role see?" — but Postgres checks table-level
-- privileges FIRST. Without a GRANT, PostgREST fails with 42501 "permission
-- denied for table ..." and never reaches the policies at all.
--
-- The Supabase posture, which this follows: grants are deliberately permissive,
-- and RLS does the real enforcement. That is safe here only because every table
-- has RLS enabled with explicit policies (see 20260718090002_rls.sql).
--
-- Idempotent — safe to re-run.
-- ============================================================================

grant usage on schema public to anon, authenticated;

-- Read: RLS then narrows this to published rows only.
grant select on all tables in schema public to anon, authenticated;

-- Write: only admins get past the is_admin() policies, but the privilege must
-- exist for the policy to even be evaluated.
grant insert, update, delete on all tables in schema public to authenticated;

-- The public contact form posts as anon.
grant insert on public.contact_messages to anon;

-- Defence in depth: anon has no business reading anyone's messages. The RLS
-- policy already restricts SELECT to admins; this removes the privilege too, so
-- a future policy mistake cannot expose them.
revoke select on public.contact_messages from anon;

-- Same reasoning for the admin roster.
revoke select on public.admin_users from anon;

grant usage, select on all sequences in schema public to anon, authenticated;

-- Anything created later inherits the same posture.
alter default privileges in schema public
  grant select on tables to anon, authenticated;
alter default privileges in schema public
  grant insert, update, delete on tables to authenticated;
alter default privileges in schema public
  grant usage, select on sequences to anon, authenticated;

-- END supabase/migrations/20260718090004_grants.sql


-- ==========================================================================
-- BEGIN supabase/seed/0001_seed.sql
-- ==========================================================================

-- ============================================================================
-- Saptham CMS — seed data
-- GENERATED by scripts/generate-seed.mjs — do not edit by hand.
-- Re-runnable: every statement upserts.
-- ============================================================================

-- ── office_bearers ─────────────────────────────────────────────────────────
insert into public.office_bearers (full_name, role, department, academic_year, image_path, bio, social, display_order) values
  ('Dhanya V', 'President', null, '2025 – 2026', null, null, '{}'::jsonb, 1),
  ('Anujan', 'President', null, '2025 – 2026', null, null, '{}'::jsonb, 2),
  ('Ratish S', 'Secretary', null, '2025 – 2026', null, null, '{}'::jsonb, 3),
  ('Vanshika', 'Secretary', null, '2025 – 2026', null, null, '{}'::jsonb, 4),
  ('Manasa', 'Head of Music', null, '2025 – 2026', null, null, '{}'::jsonb, 5),
  ('Tejaswini', 'Head of Music', null, '2025 – 2026', null, null, '{}'::jsonb, 6),
  ('Yuvati', 'Head of Dance', null, '2025 – 2026', null, null, '{}'::jsonb, 7),
  ('Pritika', 'Head of Dance', null, '2025 – 2026', null, null, '{}'::jsonb, 8),
  ('Aadhithyan', 'Head of Design & Editing', null, '2025 – 2026', null, null, '{}'::jsonb, 9),
  ('Naveen', 'Head of Design & Editing', null, '2025 – 2026', null, null, '{}'::jsonb, 10),
  ('Varshhaa Pari', 'Head of Content & Social Media', null, '2025 – 2026', null, null, '{}'::jsonb, 11),
  ('Sahana', 'Head of Content & Social Media', null, '2025 – 2026', null, null, '{}'::jsonb, 12),
  ('Harini Palaniyappan', 'Head of Logistics', null, '2025 – 2026', null, null, '{}'::jsonb, 13),
  ('Harini', 'Head of Logistics', null, '2025 – 2026', null, null, '{}'::jsonb, 14)
on conflict (full_name, academic_year) do update set
  role = excluded.role, department = excluded.department,
  bio = excluded.bio, social = excluded.social, display_order = excluded.display_order;

-- ── alumni ─────────────────────────────────────────────────────────────────
insert into public.alumni (full_name, role, tenure, graduation_year, quote, image_path, display_order) values
  ('Reshma', 'President', '''16 – ''17', 2017, 'Saptham took me from member to President, giving me opportunities, learning experiences, and a space to grow my talent and character. Organising and hosting events shaped me hugely. It is a wonderful platform for those passionate about music and performing arts and wanting to take their skills to a larger audience.', null, 1),
  ('Shraddha', 'Vice President', '''17 – ''19', 2019, 'Saptham was an ideal platform for anyone who wanted to showcase their talent in the classical arts. As the VP for 2 consecutive academic years I watched the club grow tremendously and am especially proud of how far they''ve come in the years after I graduated. Onward and upward!', null, 2),
  ('Sakthi', 'Vice President', '''20', 2020, 'SAPTHAM is an excellent organisation to explore artistic aspects. I served as secretary for a year and vice president the next. Organising performances, rehearsals, and events created unforgettable, fun-filled memories. The club provided a platform to showcase talents and connect with like-minded individuals passionate about Indian classical arts.', null, 3),
  ('Harini', 'Vice President', '''20 – ''21', 2021, 'Despite juggling many activities, Saptham was where I felt truly seen. I loved being among people dedicated to Indian classical arts. I interacted with talented artists and helped the club grow, especially during the pandemic when we had to innovate. Saptham gave me some of my best university memories.', null, 4),
  ('Meenakshi', 'President', '''21 – ''22', 2022, 'Saptham is very close to my heart. This club gave me a platform to experiment and get creative with dance. During the four years, I learnt a lot and performed on various stages, all while creating some great memories with amazing friends. My time in Saptham is something I will cherish forever.', null, 5),
  ('Ananya', 'Vice President', '''21 – ''22', 2022, 'My time as the vice president of Saptham was one of the best experiences of my college life. With countless memories and unforgettable experiences, I got to learn, explore and lead a team to help the club reach new heights. Working with like-minded people gave me a sense of satisfaction and happiness.', null, 6),
  ('Sushrut', 'Music Head', '''21 – ''22', 2022, 'Saptham is one club that always feels like home. Saptham grew from being a club no one knew about, to the club that performed its own 1.5 hour special and growing up with that was phenomenal. I met some of the wonderful people I know through Saptham, and I''ll always be a proud Saptham Alumnus!', null, 7),
  ('Viniksha', 'Batch of', '''22', 2022, 'I learnt a lot in dance during my days in Saptham club. The practice sessions before every programme are the best. It was chill, fun and I had the best experience there.', null, 8),
  ('Rose', 'Batch of', '''22', 2022, 'I joined Saptham in my second year and first performed at Agni''19. After Covid, I became more involved — helping with Saptham''s first dance drama and performing at Techofes''22. I met amazing people and made meaningful connections. My only regret is not being more involved earlier.', null, 9)
on conflict (full_name, tenure) do update set
  role = excluded.role, quote = excluded.quote, display_order = excluded.display_order;

-- ── events ─────────────────────────────────────────────────────────────────
insert into public.events (slug, title, subtitle, description, event_type, event_date, venue, display_order) values
  ('payanam', 'Payanam', 'The Golden Ages of Tamil Nadu', 'Payanam celebrated the rich heritage and history of Tamil Nadu through Bharatanatyam, a classical dance form renowned for its finesse and grace. Set to the melodious ragams of Carnatic music, the performance beautifully brought to life stories from the golden ages of Tamil culture.', 'production'::public.event_type, '2022-04-30'::date, 'Vivekananda Auditorium', 1),
  ('vishwam', 'Vishwam', 'The Divine Incarnations of Lord Narayana', 'Vishwam presented the timeless stories of Lord Vishnu''s ten avatars in a grand musical play. Combining drama, music, and devotion, the production offered an immersive journey into the divine tales of Lord Narayana.', 'production'::public.event_type, '2023-05-20'::date, 'Vivekananda Auditorium', 2),
  ('rasaleela', 'RasaLeela', 'A Complete Spectrum of Emotions', 'RasaLeela explored the full spectrum of human emotions through expressive music and dance. This annual production captured joy, love, longing, and devotion, leaving the audience enchanted by its artistry and storytelling.', 'production'::public.event_type, '2024-04-13'::date, 'Vivekananda Auditorium', 3),
  ('yaathra', 'Yaathra', 'Love, Life & Legacy', 'Yaathra wove together themes of love, longing, and devotion, presenting a journey of emotions and timeless stories. With music, movement, and expressive performances, the production offered a reflective and captivating experience for all.', 'production'::public.event_type, '2025-05-17'::date, 'Vivekananda Auditorium', 4),
  ('techofes', 'Techofes', null, 'Saptham proudly performed during the inauguration of Techofes, the flagship inter-college cultural festival of CEG, bringing music, dance, and expression to kick off the grand celebrations.', 'festival'::public.event_type, null::date, null, 10),
  ('agni', 'Agni', null, 'Saptham performed at the inaugural ceremony of Agni, CEG''s vibrant intra-college cultural fest, adding an artistic touch to the celebrations.', 'festival'::public.event_type, null::date, null, 11),
  ('vizha', 'Vizha', null, 'Saptham contributed to the inauguration of Vizha — the freshers day of CEG — celebrating creativity, tradition, and talent through music and dance.', 'festival'::public.event_type, null::date, null, 12),
  ('sampradha', 'Sampradha', null, 'Saptham performed at the opening of Sampradha, an intra-college cultural fest of ACT that showcases heritage and artistry through expressive dance and music.', 'festival'::public.event_type, null::date, null, 13),
  ('kalakrithi', 'Kalakrithi', null, 'Saptham was part of the inaugural performances of Kalakrithi, the renowned inter-college festival of ACT, adding vibrant music and dance.', 'festival'::public.event_type, null::date, null, 14),
  ('symposium-performances', 'Symposium Performances', null, 'Saptham has performed during symposium events at both CEG & ACT, enriching academic gatherings with cultural performances.', 'festival'::public.event_type, null::date, null, 15)
on conflict (slug) do update set
  title = excluded.title, subtitle = excluded.subtitle,
  description = excluded.description, event_type = excluded.event_type,
  event_date = excluded.event_date, venue = excluded.venue,
  display_order = excluded.display_order;

-- ── settings ───────────────────────────────────────────────────────────────
insert into public.settings (key, value, description) values
  ('site.title', '{"en":"Saptham","ta":"சப்தம்"}'::jsonb, 'Site name (bilingual)'),
  ('site.tagline', '{"en":"Where the seven notes become light."}'::jsonb, 'Footer blessing line'),
  ('site.current_academic_year', '{"value":"2025 – 2026"}'::jsonb, 'Drives the Office Bearers section'),
  ('contact.email', '{"value":"sapthamclassical@gmail.com"}'::jsonb, 'Primary contact address'),
  ('contact.phones', '[{"name":"Dhanya Vikram","number":"+91 88706 55694"},{"name":"Anujan","number":"+91 91767 55377"}]'::jsonb, 'Contact numbers shown on the Contact page'),
  ('social.instagram', '{"value":"https://www.instagram.com/sapthamclassical"}'::jsonb, 'Instagram'),
  ('social.youtube', '{"value":"https://www.youtube.com/@SapthamClassicalAU"}'::jsonb, 'YouTube'),
  ('social.facebook', '{"value":"https://www.facebook.com/sapthamceg"}'::jsonb, 'Facebook')
on conflict (key) do update set value = excluded.value, description = excluded.description;

-- END supabase/seed/0001_seed.sql


-- ==========================================================================
-- BEGIN supabase/migrations/20260718090003_storage.sql
-- ==========================================================================

-- ============================================================================
-- Saptham CMS — STEP 3 · Storage buckets + object policies
--
-- Run this AFTER steps 1 and 2 have committed. It is deliberately the last
-- schema step because `storage.objects` is owned by `supabase_storage_admin`,
-- and on some projects the SQL Editor role cannot create policies on it.
--
-- IF THIS STEP ERRORS, NOTHING ELSE IS LOST — steps 1, 2 and 4 are already
-- committed and the website works. Buckets marked `public` are world-readable
-- without any policy, which is all the site needs to display images. You would
-- only need the write policies to upload from the browser as an admin; those
-- can also be added in Dashboard → Storage → Policies.
--
-- All seven buckets: PUBLIC READ, ADMIN WRITE, with size caps and mime limits.
-- Idempotent.
-- ============================================================================

-- ─── Buckets ────────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('office-bearers','office-bearers', true,  10485760, array['image/jpeg','image/png','image/webp','image/avif']),
  ('alumni',        'alumni',         true,  10485760, array['image/jpeg','image/png','image/webp','image/avif']),
  ('events',        'events',         true,  15728640, array['image/jpeg','image/png','image/webp','image/avif']),
  ('gallery',       'gallery',        true,  15728640, array['image/jpeg','image/png','image/webp','image/avif']),
  ('hero',          'hero',           true,  52428800, array['image/jpeg','image/png','image/webp','image/avif','video/mp4','video/webm']),
  ('assets',        'assets',         true,  52428800, array['image/jpeg','image/png','image/webp','image/avif','image/svg+xml','video/mp4','video/webm','audio/mpeg','audio/webm']),
  ('logos',         'logos',          true,   5242880, array['image/jpeg','image/png','image/webp','image/avif','image/svg+xml'])
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- ─── Public read, one policy per bucket ─────────────────────────────────────
drop policy if exists public_read_office_bearers on storage.objects;
create policy public_read_office_bearers on storage.objects
  for select to anon, authenticated using (bucket_id = 'office-bearers');

drop policy if exists public_read_alumni on storage.objects;
create policy public_read_alumni on storage.objects
  for select to anon, authenticated using (bucket_id = 'alumni');

drop policy if exists public_read_events on storage.objects;
create policy public_read_events on storage.objects
  for select to anon, authenticated using (bucket_id = 'events');

drop policy if exists public_read_gallery on storage.objects;
create policy public_read_gallery on storage.objects
  for select to anon, authenticated using (bucket_id = 'gallery');

drop policy if exists public_read_hero on storage.objects;
create policy public_read_hero on storage.objects
  for select to anon, authenticated using (bucket_id = 'hero');

drop policy if exists public_read_assets on storage.objects;
create policy public_read_assets on storage.objects
  for select to anon, authenticated using (bucket_id = 'assets');

drop policy if exists public_read_logos on storage.objects;
create policy public_read_logos on storage.objects
  for select to anon, authenticated using (bucket_id = 'logos');

-- ─── Admin write, one policy per bucket ─────────────────────────────────────
drop policy if exists admin_write_office_bearers on storage.objects;
create policy admin_write_office_bearers on storage.objects
  for all to authenticated
  using (bucket_id = 'office-bearers' and public.is_admin())
  with check (bucket_id = 'office-bearers' and public.is_admin());

drop policy if exists admin_write_alumni on storage.objects;
create policy admin_write_alumni on storage.objects
  for all to authenticated
  using (bucket_id = 'alumni' and public.is_admin())
  with check (bucket_id = 'alumni' and public.is_admin());

drop policy if exists admin_write_events on storage.objects;
create policy admin_write_events on storage.objects
  for all to authenticated
  using (bucket_id = 'events' and public.is_admin())
  with check (bucket_id = 'events' and public.is_admin());

drop policy if exists admin_write_gallery on storage.objects;
create policy admin_write_gallery on storage.objects
  for all to authenticated
  using (bucket_id = 'gallery' and public.is_admin())
  with check (bucket_id = 'gallery' and public.is_admin());

drop policy if exists admin_write_hero on storage.objects;
create policy admin_write_hero on storage.objects
  for all to authenticated
  using (bucket_id = 'hero' and public.is_admin())
  with check (bucket_id = 'hero' and public.is_admin());

drop policy if exists admin_write_assets on storage.objects;
create policy admin_write_assets on storage.objects
  for all to authenticated
  using (bucket_id = 'assets' and public.is_admin())
  with check (bucket_id = 'assets' and public.is_admin());

drop policy if exists admin_write_logos on storage.objects;
create policy admin_write_logos on storage.objects
  for all to authenticated
  using (bucket_id = 'logos' and public.is_admin())
  with check (bucket_id = 'logos' and public.is_admin());

-- END supabase/migrations/20260718090003_storage.sql
