import { uniq } from './markdown';
import type { RegistryAsset, RegistryBatch, RegistryScene } from './schemas';

/** IDs added in CANON §6 (Workshops/Competitions/Sponsors/Join/Admin/Calendar/System) that
 *  post-date the pre-audit inventory — expected to be referenced but not yet registered. */
const CANON_ADDED = /^(WRK|CMP|SPN|JOIN|ADM|CAL|SYS|CON|NAV|SHR)-/;

export interface Gaps {
  assets_without_batch: string[];
  unknown_batch_members: { batch: string; id: string }[];
  unknown_scene_assets: { scene: string; id: string }[];
  canon_added_absent: string[];
  multi_batch_assets: { id: string; batches: string[] }[];
  notes: string[];
}

export interface Registry {
  assets: RegistryAsset[];
  batches: RegistryBatch[];
  scenes: RegistryScene[];
  gaps: Gaps;
}

/** Join assets↔batches (family/batch) and assets↔scenes (reverse index), collecting gaps. */
export function joinRegistry(
  assets: RegistryAsset[],
  batches: RegistryBatch[],
  scenes: RegistryScene[],
): Registry {
  const byId = new Map(assets.map((a) => [a.id, a]));
  const gaps: Gaps = {
    assets_without_batch: [],
    unknown_batch_members: [],
    unknown_scene_assets: [],
    canon_added_absent: [],
    multi_batch_assets: [],
    notes: [
      'Batch anchors are described by name in the roadmap → anchor_asset left null for hand-assignment.',
      'Scene priorities default to H (storyboard has no explicit per-scene priority) → hand-verify against CANON.',
      'Prompt Cards (vault/cards/**) are not generated in this M1 pass → produced from PROMPT_LIBRARY in the next increment.',
    ],
  };

  const batchOf = new Map<string, string[]>();
  for (const b of batches) {
    // The style-anchor board (family 'ref') SAMPLES assets as swatches; it never OWNS them.
    const isRef = b.family === 'ref';
    for (const id of b.members) {
      const a = byId.get(id);
      if (!a) {
        gaps.unknown_batch_members.push({ batch: b.id, id });
        continue;
      }
      if (isRef) continue;
      batchOf.set(id, [...(batchOf.get(id) ?? []), b.id]);
      if (!a.batch) {
        a.batch = b.id;
        a.family = b.family;
      }
    }
  }
  for (const [id, bs] of batchOf) if (bs.length > 1) gaps.multi_batch_assets.push({ id, batches: bs });

  for (const s of scenes) {
    for (const id of s.required_assets) {
      const a = byId.get(id);
      if (!a) {
        gaps.unknown_scene_assets.push({ scene: s.id, id });
        if (CANON_ADDED.test(id)) gaps.canon_added_absent.push(id);
        continue;
      }
      if (!a.scenes.includes(s.id)) a.scenes.push(s.id);
    }
  }

  for (const a of assets) if (!a.batch) gaps.assets_without_batch.push(a.id);
  gaps.canon_added_absent = uniq(gaps.canon_added_absent).sort();

  return { assets, batches, scenes, gaps };
}

/** Render the gap report as markdown for `vault/registry/_gaps.md`. */
export function buildGapReport(reg: Registry, skippedAssets: string[]): string {
  const { assets, batches, scenes, gaps } = reg;
  const L: string[] = [];
  L.push('# Saptham Registry — Ingestion Gap Report');
  L.push('_Generated by `npm run ingest`. Mechanical parse; items below need human resolution._\n');
  L.push('## Totals');
  L.push(`- Assets ingested: **${assets.length}**`);
  L.push(`- Batches: **${batches.length}** · Scenes: **${scenes.length}**`);
  L.push(
    `- Assets joined to a batch: **${assets.filter((a) => a.batch).length}/${assets.length}**\n`,
  );

  const section = (title: string, items: string[]) => {
    L.push(`## ${title} (${items.length})`);
    L.push(items.length ? items.map((i) => `- ${i}`).join('\n') : '_none_');
    L.push('');
  };

  section(
    'CANON-added assets referenced but NOT in the inventory',
    gaps.canon_added_absent,
  );
  section(
    'Assets with no batch (family/family unresolved)',
    gaps.assets_without_batch,
  );
  section(
    'Scene requirements that do not resolve to an asset',
    gaps.unknown_scene_assets.map((g) => `scene ${g.scene} → \`${g.id}\``),
  );
  section(
    'Batch members not found in the inventory',
    gaps.unknown_batch_members.map((g) => `${g.batch} → \`${g.id}\``),
  );
  section(
    'Assets appearing in more than one batch',
    gaps.multi_batch_assets.map((g) => `\`${g.id}\` in ${g.batches.join(', ')}`),
  );
  section('Rows skipped during parse', skippedAssets);

  L.push('## Standing notes');
  L.push(gaps.notes.map((n) => `- ${n}`).join('\n'));
  L.push('\n_— end of report —_');
  return L.join('\n');
}
