-- ============================================================================
-- Saptham CMS — seed data
-- GENERATED by scripts/generate-seed.mjs — do not edit by hand.
-- Re-runnable: every statement upserts.
-- ============================================================================

-- ── office_bearers ─────────────────────────────────────────────────────────
insert into public.office_bearers (full_name, role, department, academic_year, image_path, bio, social, display_order) values
  ('Dhanya V', 'President', null, '2025 – 2026', null, null, '{}'::jsonb, 1),
  ('Anujan', 'President', null, '2025 – 2026', null, null, '{}'::jsonb, 2),
  ('Ratish S', 'Secretary', null, '2025 – 2026', null, null, '{}'::jsonb, 3),
  ('Vanshika', 'Secretary', null, '2025 – 2026', null, null, '{}'::jsonb, 4),
  ('Manasa', 'Head of Music', null, '2025 – 2026', null, null, '{}'::jsonb, 5),
  ('Tejaswini', 'Head of Music', null, '2025 – 2026', null, null, '{}'::jsonb, 6),
  ('Yuvati', 'Head of Dance', null, '2025 – 2026', null, null, '{}'::jsonb, 7),
  ('Pritika', 'Head of Dance', null, '2025 – 2026', null, null, '{}'::jsonb, 8),
  ('Aadhithyan', 'Head of Design & Editing', null, '2025 – 2026', null, null, '{}'::jsonb, 9),
  ('Naveen', 'Head of Design & Editing', null, '2025 – 2026', null, null, '{}'::jsonb, 10),
  ('Varshhaa Pari', 'Head of Content & Social Media', null, '2025 – 2026', null, null, '{}'::jsonb, 11),
  ('Sahana', 'Head of Content & Social Media', null, '2025 – 2026', null, null, '{}'::jsonb, 12),
  ('Harini Palaniyappan', 'Head of Logistics', null, '2025 – 2026', null, null, '{}'::jsonb, 13),
  ('Harini', 'Head of Logistics', null, '2025 – 2026', null, null, '{}'::jsonb, 14)
on conflict (full_name, academic_year) do update set
  role = excluded.role, department = excluded.department,
  bio = excluded.bio, social = excluded.social, display_order = excluded.display_order;

-- ── alumni ─────────────────────────────────────────────────────────────────
insert into public.alumni (full_name, role, tenure, graduation_year, quote, image_path, display_order) values
  ('Reshma', 'President', '''16 – ''17', 2017, 'Saptham took me from member to President, giving me opportunities, learning experiences, and a space to grow my talent and character. Organising and hosting events shaped me hugely. It is a wonderful platform for those passionate about music and performing arts and wanting to take their skills to a larger audience.', null, 1),
  ('Shraddha', 'Vice President', '''17 – ''19', 2019, 'Saptham was an ideal platform for anyone who wanted to showcase their talent in the classical arts. As the VP for 2 consecutive academic years I watched the club grow tremendously and am especially proud of how far they''ve come in the years after I graduated. Onward and upward!', null, 2),
  ('Sakthi', 'Vice President', '''20', 2020, 'SAPTHAM is an excellent organisation to explore artistic aspects. I served as secretary for a year and vice president the next. Organising performances, rehearsals, and events created unforgettable, fun-filled memories. The club provided a platform to showcase talents and connect with like-minded individuals passionate about Indian classical arts.', null, 3),
  ('Harini', 'Vice President', '''20 – ''21', 2021, 'Despite juggling many activities, Saptham was where I felt truly seen. I loved being among people dedicated to Indian classical arts. I interacted with talented artists and helped the club grow, especially during the pandemic when we had to innovate. Saptham gave me some of my best university memories.', null, 4),
  ('Meenakshi', 'President', '''21 – ''22', 2022, 'Saptham is very close to my heart. This club gave me a platform to experiment and get creative with dance. During the four years, I learnt a lot and performed on various stages, all while creating some great memories with amazing friends. My time in Saptham is something I will cherish forever.', null, 5),
  ('Ananya', 'Vice President', '''21 – ''22', 2022, 'My time as the vice president of Saptham was one of the best experiences of my college life. With countless memories and unforgettable experiences, I got to learn, explore and lead a team to help the club reach new heights. Working with like-minded people gave me a sense of satisfaction and happiness.', null, 6),
  ('Sushrut', 'Music Head', '''21 – ''22', 2022, 'Saptham is one club that always feels like home. Saptham grew from being a club no one knew about, to the club that performed its own 1.5 hour special and growing up with that was phenomenal. I met some of the wonderful people I know through Saptham, and I''ll always be a proud Saptham Alumnus!', null, 7),
  ('Viniksha', 'Batch of', '''22', 2022, 'I learnt a lot in dance during my days in Saptham club. The practice sessions before every programme are the best. It was chill, fun and I had the best experience there.', null, 8),
  ('Rose', 'Batch of', '''22', 2022, 'I joined Saptham in my second year and first performed at Agni''19. After Covid, I became more involved — helping with Saptham''s first dance drama and performing at Techofes''22. I met amazing people and made meaningful connections. My only regret is not being more involved earlier.', null, 9)
on conflict (full_name, tenure) do update set
  role = excluded.role, quote = excluded.quote, display_order = excluded.display_order;

-- ── events ─────────────────────────────────────────────────────────────────
insert into public.events (slug, title, subtitle, description, event_type, event_date, venue, display_order) values
  ('payanam', 'Payanam', 'The Golden Ages of Tamil Nadu', 'Payanam celebrated the rich heritage and history of Tamil Nadu through Bharatanatyam, a classical dance form renowned for its finesse and grace. Set to the melodious ragams of Carnatic music, the performance beautifully brought to life stories from the golden ages of Tamil culture.', 'production'::public.event_type, '2022-04-30'::date, 'Vivekananda Auditorium', 1),
  ('vishwam', 'Vishwam', 'The Divine Incarnations of Lord Narayana', 'Vishwam presented the timeless stories of Lord Vishnu''s ten avatars in a grand musical play. Combining drama, music, and devotion, the production offered an immersive journey into the divine tales of Lord Narayana.', 'production'::public.event_type, '2023-05-20'::date, 'Vivekananda Auditorium', 2),
  ('rasaleela', 'RasaLeela', 'A Complete Spectrum of Emotions', 'RasaLeela explored the full spectrum of human emotions through expressive music and dance. This annual production captured joy, love, longing, and devotion, leaving the audience enchanted by its artistry and storytelling.', 'production'::public.event_type, '2024-04-13'::date, 'Vivekananda Auditorium', 3),
  ('yaathra', 'Yaathra', 'Love, Life & Legacy', 'Yaathra wove together themes of love, longing, and devotion, presenting a journey of emotions and timeless stories. With music, movement, and expressive performances, the production offered a reflective and captivating experience for all.', 'production'::public.event_type, '2025-05-17'::date, 'Vivekananda Auditorium', 4),
  ('techofes', 'Techofes', null, 'Saptham proudly performed during the inauguration of Techofes, the flagship inter-college cultural festival of CEG, bringing music, dance, and expression to kick off the grand celebrations.', 'festival'::public.event_type, null::date, null, 10),
  ('agni', 'Agni', null, 'Saptham performed at the inaugural ceremony of Agni, CEG''s vibrant intra-college cultural fest, adding an artistic touch to the celebrations.', 'festival'::public.event_type, null::date, null, 11),
  ('vizha', 'Vizha', null, 'Saptham contributed to the inauguration of Vizha — the freshers day of CEG — celebrating creativity, tradition, and talent through music and dance.', 'festival'::public.event_type, null::date, null, 12),
  ('sampradha', 'Sampradha', null, 'Saptham performed at the opening of Sampradha, an intra-college cultural fest of ACT that showcases heritage and artistry through expressive dance and music.', 'festival'::public.event_type, null::date, null, 13),
  ('kalakrithi', 'Kalakrithi', null, 'Saptham was part of the inaugural performances of Kalakrithi, the renowned inter-college festival of ACT, adding vibrant music and dance.', 'festival'::public.event_type, null::date, null, 14),
  ('symposium-performances', 'Symposium Performances', null, 'Saptham has performed during symposium events at both CEG & ACT, enriching academic gatherings with cultural performances.', 'festival'::public.event_type, null::date, null, 15)
on conflict (slug) do update set
  title = excluded.title, subtitle = excluded.subtitle,
  description = excluded.description, event_type = excluded.event_type,
  event_date = excluded.event_date, venue = excluded.venue,
  display_order = excluded.display_order;

-- ── settings ───────────────────────────────────────────────────────────────
insert into public.settings (key, value, description) values
  ('site.title', '{"en":"Saptham","ta":"சப்தம்"}'::jsonb, 'Site name (bilingual)'),
  ('site.tagline', '{"en":"Where the seven notes become light."}'::jsonb, 'Footer blessing line'),
  ('site.current_academic_year', '{"value":"2025 – 2026"}'::jsonb, 'Drives the Office Bearers section'),
  ('contact.email', '{"value":"sapthamclassical@gmail.com"}'::jsonb, 'Primary contact address'),
  ('contact.phones', '[{"name":"Dhanya Vikram","number":"+91 88706 55694"},{"name":"Anujan","number":"+91 91767 55377"}]'::jsonb, 'Contact numbers shown on the Contact page'),
  ('social.instagram', '{"value":"https://www.instagram.com/sapthamclassical"}'::jsonb, 'Instagram'),
  ('social.youtube', '{"value":"https://www.youtube.com/@SapthamClassicalAU"}'::jsonb, 'YouTube'),
  ('social.facebook', '{"value":"https://www.facebook.com/sapthamceg"}'::jsonb, 'Facebook')
on conflict (key) do update set value = excluded.value, description = excluded.description;
