#!/usr/bin/env node
/**
 * Generates supabase/seed/0001_seed.sql from the live JSON content files.
 *
 *   node scripts/generate-seed.mjs
 *
 * Office bearers + alumni come straight from src/data/*.json (the current source
 * of truth). Events are transcribed from the Events page. The output is
 * idempotent (ON CONFLICT ... DO UPDATE) so it can be re-applied safely.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => JSON.parse(readFileSync(resolve(root, p), "utf8"));

/** SQL string literal (null-safe, quote-escaping). */
const s = (v) =>
  v === null || v === undefined || v === "" ? "null" : `'${String(v).replace(/'/g, "''")}'`;
const n = (v) => (v === null || v === undefined || v === "" ? "null" : Number(v));
const j = (v) => `'${JSON.stringify(v ?? {}).replace(/'/g, "''")}'::jsonb`;

const officeBearers = read("src/data/officeBearers.json");
const alumni = read("src/data/alumni.json");

/** "'21 – '22" → 2022 (last 2-digit year mentioned), else null. */
function gradYear(tenure) {
  const years = String(tenure ?? "").match(/\d{2}/g);
  if (!years) return null;
  return 2000 + Number(years[years.length - 1]);
}

const EVENTS = [
  {
    slug: "payanam", title: "Payanam", subtitle: "The Golden Ages of Tamil Nadu",
    type: "production", date: "2022-04-30", venue: "Vivekananda Auditorium", order: 1,
    description:
      "Payanam celebrated the rich heritage and history of Tamil Nadu through Bharatanatyam, a classical dance form renowned for its finesse and grace. Set to the melodious ragams of Carnatic music, the performance beautifully brought to life stories from the golden ages of Tamil culture.",
  },
  {
    slug: "vishwam", title: "Vishwam", subtitle: "The Divine Incarnations of Lord Narayana",
    type: "production", date: "2023-05-20", venue: "Vivekananda Auditorium", order: 2,
    description:
      "Vishwam presented the timeless stories of Lord Vishnu's ten avatars in a grand musical play. Combining drama, music, and devotion, the production offered an immersive journey into the divine tales of Lord Narayana.",
  },
  {
    slug: "rasaleela", title: "RasaLeela", subtitle: "A Complete Spectrum of Emotions",
    type: "production", date: "2024-04-13", venue: "Vivekananda Auditorium", order: 3,
    description:
      "RasaLeela explored the full spectrum of human emotions through expressive music and dance. This annual production captured joy, love, longing, and devotion, leaving the audience enchanted by its artistry and storytelling.",
  },
  {
    slug: "yaathra", title: "Yaathra", subtitle: "Love, Life & Legacy",
    type: "production", date: "2025-05-17", venue: "Vivekananda Auditorium", order: 4,
    description:
      "Yaathra wove together themes of love, longing, and devotion, presenting a journey of emotions and timeless stories. With music, movement, and expressive performances, the production offered a reflective and captivating experience for all.",
  },
  { slug: "techofes", title: "Techofes", type: "festival", order: 10,
    description: "Saptham proudly performed during the inauguration of Techofes, the flagship inter-college cultural festival of CEG, bringing music, dance, and expression to kick off the grand celebrations." },
  { slug: "agni", title: "Agni", type: "festival", order: 11,
    description: "Saptham performed at the inaugural ceremony of Agni, CEG's vibrant intra-college cultural fest, adding an artistic touch to the celebrations." },
  { slug: "vizha", title: "Vizha", type: "festival", order: 12,
    description: "Saptham contributed to the inauguration of Vizha — the freshers day of CEG — celebrating creativity, tradition, and talent through music and dance." },
  { slug: "sampradha", title: "Sampradha", type: "festival", order: 13,
    description: "Saptham performed at the opening of Sampradha, an intra-college cultural fest of ACT that showcases heritage and artistry through expressive dance and music." },
  { slug: "kalakrithi", title: "Kalakrithi", type: "festival", order: 14,
    description: "Saptham was part of the inaugural performances of Kalakrithi, the renowned inter-college festival of ACT, adding vibrant music and dance." },
  { slug: "symposium-performances", title: "Symposium Performances", type: "festival", order: 15,
    description: "Saptham has performed during symposium events at both CEG & ACT, enriching academic gatherings with cultural performances." },
];

const L = [];
L.push("-- ============================================================================");
L.push("-- Saptham CMS — seed data");
L.push("-- GENERATED by scripts/generate-seed.mjs — do not edit by hand.");
L.push("-- Re-runnable: every statement upserts.");
L.push("-- ============================================================================");
L.push("");

// ── office_bearers ──────────────────────────────────────────────────────────
L.push("-- ── office_bearers ─────────────────────────────────────────────────────────");
L.push(
  "insert into public.office_bearers (full_name, role, department, academic_year, image_path, bio, social, display_order) values",
);
L.push(
  officeBearers.members
    .map((m, i) =>
      `  (${s(m.name)}, ${s(m.role)}, ${s(m.department)}, ${s(officeBearers.year)}, ` +
      `${s(m.image)}, ${s(m.bio)}, ${j(m.social)}, ${i + 1})`,
    )
    .join(",\n"),
);
L.push("on conflict (full_name, academic_year) do update set");
L.push("  role = excluded.role, department = excluded.department,");
L.push("  bio = excluded.bio, social = excluded.social, display_order = excluded.display_order;");
L.push("");

// ── alumni ──────────────────────────────────────────────────────────────────
L.push("-- ── alumni ─────────────────────────────────────────────────────────────────");
L.push("insert into public.alumni (full_name, role, tenure, graduation_year, quote, image_path, display_order) values");
L.push(
  alumni.members
    .map((m, i) =>
      `  (${s(m.name)}, ${s(m.role)}, ${s(m.year)}, ${n(gradYear(m.year))}, ` +
      `${s(m.quote)}, ${s(m.image)}, ${i + 1})`,
    )
    .join(",\n"),
);
L.push("on conflict (full_name, tenure) do update set");
L.push("  role = excluded.role, quote = excluded.quote, display_order = excluded.display_order;");
L.push("");

// ── events ──────────────────────────────────────────────────────────────────
L.push("-- ── events ─────────────────────────────────────────────────────────────────");
L.push("insert into public.events (slug, title, subtitle, description, event_type, event_date, venue, display_order) values");
L.push(
  EVENTS.map(
    (e) =>
      `  (${s(e.slug)}, ${s(e.title)}, ${s(e.subtitle)}, ${s(e.description)}, ` +
      `${s(e.type)}::public.event_type, ${s(e.date)}::date, ${s(e.venue)}, ${e.order})`,
  ).join(",\n"),
);
L.push("on conflict (slug) do update set");
L.push("  title = excluded.title, subtitle = excluded.subtitle,");
L.push("  description = excluded.description, event_type = excluded.event_type,");
L.push("  event_date = excluded.event_date, venue = excluded.venue,");
L.push("  display_order = excluded.display_order;");
L.push("");

// ── settings ────────────────────────────────────────────────────────────────
L.push("-- ── settings ───────────────────────────────────────────────────────────────");
const settings = [
  ["site.title", { en: "Saptham", ta: "சப்தம்" }, "Site name (bilingual)"],
  ["site.tagline", { en: "Where the seven notes become light." }, "Footer blessing line"],
  ["site.current_academic_year", { value: officeBearers.year }, "Drives the Office Bearers section"],
  ["contact.email", { value: "sapthamclassical@gmail.com" }, "Primary contact address"],
  ["contact.phones", [
    { name: "Dhanya Vikram", number: "+91 88706 55694" },
    { name: "Anujan", number: "+91 91767 55377" },
  ], "Contact numbers shown on the Contact page"],
  ["social.instagram", { value: "https://www.instagram.com/sapthamclassical" }, "Instagram"],
  ["social.youtube", { value: "https://www.youtube.com/@SapthamClassicalAU" }, "YouTube"],
  ["social.facebook", { value: "https://www.facebook.com/sapthamceg" }, "Facebook"],
];
L.push("insert into public.settings (key, value, description) values");
L.push(settings.map(([k, v, d]) => `  (${s(k)}, ${j(v)}, ${s(d)})`).join(",\n"));
L.push("on conflict (key) do update set value = excluded.value, description = excluded.description;");
L.push("");

mkdirSync(resolve(root, "supabase/seed"), { recursive: true });
const out = resolve(root, "supabase/seed/0001_seed.sql");
writeFileSync(out, L.join("\n"), "utf8");

console.log(`✓ seed written → supabase/seed/0001_seed.sql`);
console.log(
  `  office_bearers: ${officeBearers.members.length}  alumni: ${alumni.members.length}  ` +
    `events: ${EVENTS.length}  settings: ${settings.length}`,
);
